export const booksData = [
  {
    id: 1,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Non-Fiction",
    description:
      "A practical guide to building good habits and breaking bad ones.",
    rating: 4.8,
    image: "https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg",
  },
  {
    id: 2,
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    description: "A philosophical novel about following your dreams.",
    rating: 4.6,
    image: "https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg",
  },
  {
    id: 3,
    title: "Dune",
    author: "Frank Herbert",
    category: "Sci-Fi",
    description:
      "An epic science fiction novel set on the desert planet Arrakis.",
    rating: 4.7,
    image: "https://m.media-amazon.com/images/I/41JVFor1FpL._SY445_SX342_ControlCacheEqualizer_.jpg",
  },
  {
    id: 4,
    title: "Clean Code",
    author: "Robert C. Martin",
    category: "Non-Fiction",
    description: "A handbook of agile software craftsmanship.",
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/41nUxzDHD-L._SY445_SX342_ControlCacheEqualizer_.jpg",
  },
  {
    id: 5,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    category: "Fiction",
    description: "The magical beginning of Harry Potter’s journey.",
    rating: 4.9,
    image: "https://images-na.ssl-images-amazon.com/images/I/81YOuOGFCJL.jpg",
  },
  {
    id: 6,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    category: "Non-Fiction",
    description: "Essential tips for modern software developers.",
    rating: 4.6,
    image: "https://images-na.ssl-images-amazon.com/images/I/71f1jieYHNL.jpg",
  },
  {
    id: 7,
    title: "1984",
    author: "George Orwell",
    category: "Fiction",
    description: "A dystopian novel about surveillance and totalitarianism.",
    rating: 4.7,
    image: "https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg",
  },
  {
    id: 8,
    title: "The Martian",
    author: "Andy Weir",
    category: "Sci-Fi",
    description: "A survival story of an astronaut stranded on Mars.",
    rating: 4.6,
    image: "https://images-na.ssl-images-amazon.com/images/I/81WcnNQ-TBL.jpg",
  },
  {
    id: 9,
    title: "Think Like a Monk",
    author: "Jay Shetty",
    category: "Non-Fiction",
    description: "Timeless wisdom for reducing stress and finding purpose.",
    rating: 4.4,
    image: "https://images-na.ssl-images-amazon.com/images/I/71KilybDOoL.jpg",
  },
  {
    id: 10,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    category: "Fiction",
    description: "A fantasy adventure preceding The Lord of the Rings.",
    rating: 4.8,
    image: "https://images-na.ssl-images-amazon.com/images/I/91b0C2YNSrL.jpg",
  },
  {
    id: 11,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
    description: "A brief history of humankind.",
    rating: 4.7,
    image: "https://images-na.ssl-images-amazon.com/images/I/713jIoMO3UL.jpg",
  },
  {
    id: 12,
    title: "Foundation",
    author: "Isaac Asimov",
    category: "Sci-Fi",
    description: "A science fiction saga about the fall of a galactic empire.",
    rating: 4.5,
    image: "https://images-na.ssl-images-amazon.com/images/I/81vpsIs58WL.jpg",
  },
  {
    id: 13,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    category: "Non-Fiction",
    description: "Lessons about money, investing, and financial independence.",
    rating: 4.3,
    image: "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
  },
  {
    id: 14,
    title: "Brave New World",
    author: "Aldous Huxley",
    category: "Fiction",
    description: "A dystopian future shaped by technology and control.",
    rating: 4.4,
    image: "https://images-na.ssl-images-amazon.com/images/I/81zE42gT3xL.jpg",
  },
  {
    id: 15,
    title: "Neuromancer",
    author: "William Gibson",
    category: "Sci-Fi",
    description: "A cyberpunk novel that shaped modern science fiction.",
    rating: 4.3,
    image: "https://m.media-amazon.com/images/I/81m-rJnUdRL._SY425_.jpg",
  },
];
